### ISSUE TITLE
Version tags and releases

### ISSUE THREAD

**Issue by yurtpage** [blocktrron/cudy-bdinfo-decrypt#1]
Could you please add a git tag for a release version and ideally also create a release on the GitHub
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository

This is a common practice and helps a lot for package maintainers.
Your package is used in OpenWrt feed and it's used a commit hash instead of a version. This is incovinient

**Comment by blocktrron** [comment]
I maintain this package there and there is no need to do so.
